source 'https://rubygems.org'

gem 'ruby-trello', '3.2.0'

group :development, :test do
  gem 'rake', '~> 13.2.1'
  gem 'rspec', '~> 3.12.0'
  gem 'rubocop', '~> 0.93.0', require: false
  gem 'rubocop-rspec', '~> 1.44.1', require: false
end
