source 'https://rubygems.org'

gem 'ruby-trello', '2.3.1'

group :development, :test do
  gem 'rake', '~> 13.0.0'
  gem 'rspec', '~> 3.9.0'
  gem 'rubocop', '~> 0.93.0', require: false
  gem 'rubocop-rspec', '~> 1.43.0', require: false
end
